version: '2'
services:
  mono-app:
    image: mono
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://mono-mysql:3306/mono?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - KAFKA_CONSUMER_KEY_DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
      - KAFKA_CONSUMER_VALUE_DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
      - KAFKA_CONSUMER_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CONSUMER_GROUP_ID=mono
      - KAFKA_CONSUMER_AUTO_OFFSET_RESET=earliest
      - KAFKA_PRODUCER_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_PRODUCER_KEY_DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
      - KAFKA_PRODUCER_VALUE_DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
    ports:
      - 8080:8080
  mono-mysql:
    extends:
      file: mysql.yml
      service: mono-mysql
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
