version: '2'
services:
    mysql-app:
        image: mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://mysql-mssql:1433;database=tempdb
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mysql-mssql:
        extends:
            file: mssql.yml
            service: mysql-mssql
