version: '2'
services:
    session-app:
        image: session
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://session-mysql:3306/session?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    session-mysql:
        extends:
            file: mysql.yml
            service: session-mysql
