version: '2'
services:
    jhipsterwebsocketsampleapplication-app:
        image: jhipsterwebsocketsampleapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterwebsocketsampleapplication-mysql:3306/jhipsterwebsocketsampleapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - APPLICATION_STOMP_BROKER_URL=rabbitmq
            - APPLICATION_STOMP_BROKER_USERNAME=rabbitmq-username
            - APPLICATION_STOMP_BROKER_PASSWORD=rabbitmq-password
        ports:
            - 8080:8080
    jhipsterwebsocketsampleapplication-app2:
        image: jhipsterwebsocketsampleapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterwebsocketsampleapplication-mysql:3306/jhipsterwebsocketsampleapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - APPLICATION_STOMP_BROKER_URL=rabbitmq
            - APPLICATION_STOMP_BROKER_USERNAME=rabbitmq-username
            - APPLICATION_STOMP_BROKER_PASSWORD=rabbitmq-password
        ports:
            - 8081:8080
    jhipsterwebsocketsampleapplication-mysql:
        extends:
            file: mysql.yml
            service: jhipsterwebsocketsampleapplication-mysql
    rabbitmq:
        extends:
            file: rabbitmq.yml
            service: rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=rabbitmq-username
            - RABBITMQ_DEFAULT_PASS=rabbitmq-password
